### ISSUE TITLE
Feature errors as well

### ISSUE THREAD

**Issue by pykong** [alexkuz/SublimeLinter-inline-errors#1]
@alexkuz Thanks for this awesome plugin! It fills a gap for me.

I would love to see not only warnings but also errors displayed inline.
They should feature a distinct symbol of a red theme.

I guess a red cross sign, like this [one](https://t3.ftcdn.net/jpg/01/11/33/40/500_F_111334076_eDzY5U43oumaDNe92zr7bifJ5jRmjSsD.jpg) is a convention for this purpose.

**Comment by alexkuz** [comment]
Try to install the latest version from Package Control (make sure you've removed the older one and removed https://github.com/alexkuz/SublimeLinter-inline-errors from Package Control repos)

**Comment by pykong** [comment]
@alexkuz Indeed I noticed you have now implemented the display of errors.
Top notch Plugin-In! Thank You!
