### ISSUE TITLE
Lots of numbers printed on the console on each selection change

### ISSUE THREAD

**Issue by FichteFoll** [alexkuz/SublimeLinter-inline-errors#10]
I've determined this package to be the culprit for numerous numbers being printed on the console whenver I change the selection in a view that has linter errors or warning. Please remove them; they are very annoying.

Excerpt:
```
SublimeLinter: sublimesyntax activated: <builtin> 
SublimeLinter: annotations activated: <builtin> 
52 48
54 46
18 82
52 48
54 46
18 82
52 48
54 46
18 82
52 48
54 46
18 82
52 48
54 46
18 82
SublimeLinter: sublimesyntax activated: <builtin> 
SublimeLinter: annotations activated: <builtin> 
52 48
54 46
18 82
52 48
54 46
18 82
52 48
54 46
18 82
52 48
54 46
18 82
```

Suspected code producing them:

https://github.com/alexkuz/SublimeLinter-inline-errors/blob/fa82a0ff590482fa17ef493296702e438911fd60/inline-errors.py#L365-L367

**Comment by alexkuz** [comment]
Yes, sorry for that, updated version should be available soon.
