### ISSUE TITLE
Enhancements 

### ISSUE THREAD

**Issue by ctf0** [alexkuz/SublimeLinter-inline-errors#2]
- package
    - the settings are directing to `Packages/SublimeLinter-inline-errors` which is not found because the package is under `Installed Packages`
    - when the package is extracted the folder name is `SublimeLinter Inline Errors` not `SublimeLinter-inline-errors` so the settings wont work
    - it would be better if we have a user settings option instead of relying on the package default.

- i know its still in beta but here are a couple of issues if you are collecting such a thing
    - the error is duplicated
    - the hint bg color is white

![screen shot 2017-08-19 at 2 19 49 am](https://user-images.githubusercontent.com/7388088/29481739-12c7c4e6-8485-11e7-9968-2429ed175c36.jpg)

**Comment by alexkuz** [comment]
Not sure where is that background coming from, maybe some other plugin styles affects it?
Try to install the latest version from `Package Control` (make sure you've removed the older one and removed `https://github.com/alexkuz/SublimeLinter-inline-errors` from Package Control repos)

**Comment by ctf0** [comment]
thanx, solved all the issues.

btw `min_gap` is the same as `min_offset`, or is it diff ?

**Comment by alexkuz** [comment]
@ctf0 the difference is that `min_gap` is relative to the end of a line (so that between line and hint is at least `min_gap`-wide free space), while `min_offset` is absolute (hint is showed at `min_offset` position or further)
