### ISSUE TITLE
[feature] show/update the linter on view activate/updated

### ISSUE THREAD

**Issue by ctf0** [alexkuz/SublimeLinter-inline-errors#4]
atm it only show if we moved the cursor.

maybe we can hook the phantom on/off by the sublime-linter events

**Comment by alexkuz** [comment]
This plugin monkey-patches SublimeLinter to track the updates, so I think it should work in current version, please let me know if it's not.

**Comment by ctf0** [comment]
thanx for the new updates, however this one still doesnt behave as expected.

to produce :

- open  a file with an error or warning
- sublime linter will show something in the gutter automaticlly
- if u dont move the cursor, you wont see the inline icon.

**Comment by alexkuz** [comment]
I can't reproduce it, unfortunately, it shows a hint right after sublimelinter highlighting:
![2017-08-29 at 13 06](https://user-images.githubusercontent.com/790659/29815967-1d87b57e-8cbb-11e7-819c-7d96b1ce074f.gif)

**Comment by ctf0** [comment]
enable the gutter them for sublime linter and you should see the errors icon in the gutter.

what i was hoping for, is to have the inline error to behave the same "without any interaction from the user side"
