### ISSUE TITLE
Add alternative symbols.

### ISSUE THREAD

**Issue by pykong** [alexkuz/SublimeLinter-inline-errors#6]
It would be great if you added a small selection of alternative symbols into a comment of the settings file.

This would make customisation easier and much more fun.

Popular plugins like PlainTasks or PythonBreaktpoints, which feature special symbols are doing it the same way.

**Comment by alexkuz** [comment]
I guess you have some in mind - if so, please make a PR.

**Comment by pykong** [comment]
Done. Ditch those symbols you do not like.
