### ISSUE TITLE
[feature] option to hide the inline error

### ISSUE THREAD

**Issue by ctf0** [alexkuz/SublimeLinter-inline-errors#7]
in sublime-linter you can make the warning passive, which only shows the gutter theme but not in the errors list.

so is it possible to do the same for the warning & error, so the user can decide whether to show the inline errors or not ?

yes we can solve this by removing the error type symbol, but you will be left with the `offset_symbol` remaining visible.

**Comment by alexkuz** [comment]
`show_errors` and `show_warnings` will be available in `0.0.5`

**Comment by ctf0** [comment]
thanx

**Comment by ctf0** [comment]
**update**

the show and hide, effects the inline msg it self but it needs to effect the `offset_symbol` as well as the corresponding status icon `error / warning`

**Comment by alexkuz** [comment]
Oh, you're right, missed that somehow.
