### ISSUE TITLE
Display messages in output panel instead of inserting it into buffer.

### ISSUE THREAD

**Issue by pykong** [alexkuz/SublimeLinter-inline-errors#9]
I'd prefer the text of a warning/error not to be mixed with my code at all.
A better way would be to just show the symbol.
Clicking the symbol would then open an output panel hovering in proximity to the symbol and being filled with the respective warning/error message.

See this thread on Sublime Forum for technical instructions on output panels:
https://forum.sublimetext.com/t/context-menu-for-output-panel/25849/7

**Comment by FichteFoll** [comment]
Output panels are always placed at the bottom of the window. Maybe you want popups instead?

**Comment by pykong** [comment]
@FichteFoll Popups would be a clear improvement over my original suggestion. I am not sure though they're supported in the API. Maybe you know differently?

**Comment by FichteFoll** [comment]
I mean, there is `View.show_popup`.

**Comment by pykong** [comment]
@alexkuz What do you think about my suggestion to display error messages in popups instead Don't you think this would be a cleaner way for message display?

**Comment by alexkuz** [comment]
I personally don't like popups that much, but I guess it can be an option.
There is/was a PR or something in SublimeLinter itself, as I recall, I tried it and it felt a bit annoying - but maybe that was just unfortunate implementation.

**Comment by pykong** [comment]
@alexkuz AFAIK anaconda features pop-ups for display of signatures and other info. It never felt annoying to me and blends well into Sublime, in terms of optics and UX.

Would you accept a PR, if I implemented popups and they do NOT feel annoying?
(Of course, I need to know before deep diving into this. ;-)) Maybe we could make display via popups a settings option.

**Comment by alexkuz** [comment]
Sure, go ahead! Shouldn't be too hard (except for my messy code)

**Comment by pykong** [comment]
@alexkuz I have not looked into your code yet at all. Do not mind it being messy, I clean up python code regularly.

Great, let's do this!

I will come back in a week or earlier.

**Comment by pykong** [comment]
@alexkuz I am sorry but the code of your plugin is currently beyond my understanding. Especially the use of descriptors I find very confusing. I have not been able to pass an additional string argument to `on_navigate` to transmit HTML content from upstream methods.

I may try at a different time to implement the inline display of plugins.

Still, this plugin has major potential. Keep up the good work!
